### ISSUE TITLE
Падает на выражении

### ISSUE THREAD

**Issue by pomponchik** [pomponchik/computor_v1#1]
"3 * X^2 = 3 * X^2"

**Comment by pomponchik** [comment]
Вывод:
`Reduced form: 0 * X^2 = 0
Polynomial degree: 0
Traceback (most recent call last):
  File "/Users/ahalmon-/Desktop/comp/computor.py", line 19, in <module>
    print(expression.solve())
  File "/Users/ahalmon-/Desktop/comp/srcs/expression.py", line 42, in solve
    if self[0].number.content != 0:
  File "/Users/ahalmon-/Desktop/comp/srcs/expression.py", line 24, in __getitem__
    raise KeyError(f'Expression "{self}" has no element with the degree "{key}"')
KeyError: 'Expression "0 * X^2 = 0" has no element with the degree "0"'`

**Comment by pomponchik** [comment]
Исправил.
